# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from pathlib import Path
from ...agents import FeedbackConfig
from ...agents.opt_ncu_rl import RLNCUAgent
from ..state import GraphState, save_state_to_json
from ...config import config, GPUType


async def optimization_rl_ncu(state: GraphState):
    """
    RL-based NCU optimization node.
    This node takes the CUDA kernel generated by the standard workflow
    and applies RL-based optimization using the RLNCUAgent.
    
    Requires curated CUDA files (driver.cpp and init.cu) from data/kernelbench-cuda.
    If these files are not available, the problem is skipped gracefully.
    """
    base_folder = Path(state["folder"])
    base_folder.mkdir(parents=True, exist_ok=True)
    
    # Prefer loading curated artifacts from data/kernelbench-cuda instead of relying
    # on pre-existing files in the per-run output folder.
    # We derive <level>/<problem_name> from the run folder, which is already structured
    # like .../level1/<problem_name>/.
    # In the container this file is at:
    #   /kernelblaster/src/kernelblaster/graph/nodes/optimization_rl_ncu.py
    # so parents[4] == /kernelblaster (repo root).
    repo_root = Path(__file__).resolve().parents[4]
    curated_root = Path(state.get("kernelbench_cuda_root", repo_root / "data/kernelbench-cuda"))
    level = base_folder.parent.name
    problem_name = base_folder.name
    curated_dir = curated_root / level / problem_name

    curated_driver_cpp = curated_dir / "driver.cpp"
    curated_init_cu = curated_dir / "init.cu"

    # Fallbacks: allow using files that already exist in the run folder.
    run_driver_cpp = base_folder / "driver.cpp"
    run_init_cu = base_folder / "init.cu"
    
    # Handle missing cuda_fp - require curated or run-folder init.cu
    cuda_fp = state.get("cuda_fp")
    if cuda_fp is None:
        if curated_init_cu.exists():
            cuda_fp = curated_init_cu
            state["logger"].info(f"Using curated init.cu from {curated_dir} as cuda_fp: {cuda_fp}")
        elif run_init_cu.exists():
            cuda_fp = run_init_cu
            state["logger"].info(f"Using run-folder init.cu as cuda_fp: {cuda_fp}")
        else:
            state["logger"].error(
                f"No cuda_fp available. Required files not found:\n"
                f"  - Curated: {curated_init_cu}\n"
                f"  - Run folder: {run_init_cu}\n"
                f"Skipping problem {problem_name} - curated CUDA files are required."
            )
            return {"rl_ncu_cuda_fp": None}

    cuda_fp = Path(cuda_fp)
    
    # Handle missing test_code_fp - require curated or run-folder driver.cpp
    test_code_fp = state.get("test_code_fp")
    if test_code_fp is None:
        if curated_driver_cpp.exists():
            test_code_fp = curated_driver_cpp
            state["logger"].info(f"Using curated driver.cpp from {curated_dir} as test_code_fp: {test_code_fp}")
        elif run_driver_cpp.exists():
            test_code_fp = run_driver_cpp
            state["logger"].info(f"Using run-folder driver.cpp as test_code_fp: {test_code_fp}")
        else:
            state["logger"].error(
                f"No test_code_fp available. Required files not found:\n"
                f"  - Curated: {curated_driver_cpp}\n"
                f"  - Run folder: {run_driver_cpp}\n"
                f"Skipping problem {problem_name} - curated driver.cpp is required."
            )
            return {"rl_ncu_cuda_fp": None}
    
    test_code_fp = Path(test_code_fp)
    
    save_state_to_json(state, base_folder / "state.json")

    # Create RL agent configuration
    fb_config = FeedbackConfig(
        agent_name="rl_ncu",
        base_folder=base_folder,
        logger=state["logger"],
        init_user_prompt="",  # This will be set in RLNCUAgent.initialize()
        model=state["model"],
        gpu=state["gpu"],
        test_code_fp=test_code_fp,
        retry_failed=state["retry_failed"],
        num_pgen=4,  # RL agent uses fewer parallel coders since it's more strategic
    )
    
    # Get RL parameters from state (passed from workflow config)
    database_path = base_folder.parent.parent.parent / "optimization_database.md"
    max_rollout_steps = state.get("rl_rollout_steps", 5)
    replay_buffer_size = state.get("rl_buffer_size", 100)
    update_frequency = state.get("rl_update_frequency", 3)
    rl_iterations = state.get("rl_iterations", 10)
    
    agent_rl_ncu = RLNCUAgent(
        fb_config=fb_config,
        code_to_optimize_fp=cuda_fp,
        database_path=database_path,
        max_rollout_steps=max_rollout_steps,
        replay_buffer_size=replay_buffer_size,
        update_frequency=update_frequency,
        database=state.get("shared_optimization_database"),
    )
    
    # Initialize and run RL optimization
    await agent_rl_ncu.initialize()
    
    # Run RL optimization with multiple iterations
    state["logger"].info(f"Starting RL optimization with {rl_iterations} iterations")
    
    # Set the number of iterations in the agent
    agent_rl_ncu.num_rl_iterations = rl_iterations
    
    # Run the RL agent (it will handle multiple iterations internally)
    best_filename = await agent_rl_ncu.run()
    
    if best_filename is not None:
        state["logger"].info(f"RL optimization completed successfully: {best_filename}")
    else:
        state["logger"].error("RL optimization failed to produce any valid results")

    # Save the best result
    if best_filename is not None:
        final_file = base_folder / "final_rl_cuda_perf.cu"
        final_file.write_text(best_filename.read_text())
        state["logger"].info(f"RL optimization completed. Best result saved to {final_file}")
    else:
        state["logger"].error("RL optimization failed to produce any valid results")

    save_state_to_json({**state, "rl_ncu_cuda_fp": best_filename}, base_folder / "state.json")

    return {"rl_ncu_cuda_fp": best_filename} 